// Code generated by newapi. DO NOT EDIT. !!此行存在则会被生成器覆盖!!
// State 获取API服务状态 GET /state 系统API TODO
package services

import (
	"PROJECT_NAME/schemas"
	"context"
	"github.com/gin-gonic/gin"
)

func StateSetMiddleware() []gin.HandlerFunc {
	return []gin.HandlerFunc{}
}

// StateService godoc
//
//	@Summary		State
//	@Description	获取API服务状态
//	@Tags			系统API
//	@Router			/state [GET]
//	@Accept			json
//	@Produce		json
//	@Param			req		body		schemas.StateServiceReq	true	"请求体"
//	@Success		200		{object}	schemas.StateServiceResp
func StateService(c context.Context, req *schemas.StateServiceReq) (resp *schemas.StateServiceResp, err error) {
	resp = new(schemas.StateServiceResp)
	return
}
